name: Live Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-live-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: uparzone.com
          username: uparzone
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABArOy34fg
            k1p+iw1rzKd6XVAAAAEAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQC7NwtO6ro2
            99NjzQJ8hS5HN2RJxr3/MdIC5J7BcV/MZAvRmOUdYC9ilVXsg/Tj79o2lFvjWU/CRNQ3yr
            pw/FSS5c8mf/gUZAV2aJAo9NBIVxqZFlZoKXP6KuL/PdJ/A2WjPy8mbEd+U0J2kUqBzuda
            7flcQD7PWR6jfP96nhdxSQDFcmRXiel1av+IaRtfOC6nOjJUydeCDJDdeJWgeV6hfeRsaQ
            4goLaH1LfZhou1W3ppoPCYpEuJKym/+jOmMNimz5vvFfWfo5QMay2YIyvxqPeeW0iCM4VQ
            sHjigXquW2mGVWVK9YHu7tR77Tk27EmSyJWjm3xA/BbQfRzgnXuzAAADwJhH9D2cLryeI3
            NWu1CRGkiDjGyomViJmkSfhiunRtdbrKlzEpO3MV5DZmauY/z0wttNv1WIEyykqEMNFux7
            bQgjIb9Qvl2s0jiHjhVxfnXauV1v37EHonDnZLn+rO6IGWHd9XMNlz58tT8HzB3v6r848l
            cRRGZJIALe0o0K9TB53xsIHlTW0Sq+yzOD4MHEwYo2yMvIOBFkA3u7m1ZrPRg/gkn6gLnK
            z4Lioxk6obwJcz8SeHFWZZJUldEhjSRWmZwU3GfecKfJ8uxoSIBHs+S49hI29LIwGBgGoh
            M3pfuUy3eYldg2ldLeoZ8UKudoXM06HJMRYIV9OTxg04moUUxpb0OmY7BPRb75d7Jnm0VF
            zX4HTos3dAMsAA5AoKLZ1QR5TCQxCMtl8z/bCq0tXVTpRIzsMntrVbykqezhVdcQa53Zs/
            niGIU0CXyUVvUrs4f0PDvEK+dKlVOcpEXuLO2c08obWrOo5f+VXeS8E890x+7gqk4Uii+c
            vhHeMLdcP37SLdyeUUa59Qj6YmqJKsqU7W8JysC6ZWtKmrc4pA4BbzCzFERX/RX3z9AZrX
            p2ybTNskquVN/ovXq6UpD0tAPqN1y98au1Za/BdogB+oz0y8koubnTg17WNLuyvudHNeVy
            ARUQh5kZu82oFpkyzq0bOGOB/1Zw8TwTatE7MLDGr0K05FLcv8rfI5quY/ZTJ/O1aedPHT
            trSAHVwZgFAUjrJTsg/p+9DRu5clOR0j3XXrOwJJgbt9JrzvelXk/TkVQQr56aBTmG1+wO
            xWXN5zqYEX1zTwANUeGAsKJ/SkrnkNQ4hOOV11EZBs9SzKFetU7ojBmjIUcTpWri2f82cy
            Rj329gWIC/l+e3UF+a3YL2+hv9+kde3bLAdhJ+1Tqar/DmCBX+okSDTXZ7XwAnEuzYcuIe
            2TTRfgPegAcR+xy1nH3tOqRo6G6udZEeYREazWSFpV8y3y56VmtW4eZacvyecCucksLhsH
            qaGdihm7p0XmUyRviAVZq9YxGHKwMqhGNQgFRV4NtxTZvfEROiTpKMtaiNeEweq2V3ZX4E
            BDr/JMLodoukO9LuszL061Uth7+e7e3epVE/iYNujYmUFdKL3e9D33pU+EkFtZPnRl8oFV
            pRzeT7mdAG/XzDyFWMlWhJenHCxtErak+Bf5QWllFdQ++gdu3x5Ut2/DzRphHO7jQ9Qts1
            QTkg9VdrcPYXzzeiqenEAwcz113+OSlcoIn1q+L/xXHEyysrugxJwd34rjHusGo2zvfdwk
            8TtZPssg==
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          passphrase: uparzone-v2
          script: |
            cd new.uparzone.com
            git fetch --all
            git reset --hard origin/main
            git pull

