name: Deploy to CapRover (Image Method)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CONTEXT_DIR: './'
      DOCKERFILE: 'dockerfile'
      CAPROVER_APP: 'uparzone-v2-prod'
      DOCKER_REGISTRY: 'ghcr.io'

    steps:
      - uses: actions/checkout@v3

      - name: Set image name
        run: |
          echo "GH_USERNAME=${{ secrets.GH_USERNAME }}" >> $GITHUB_ENV
          echo "IMAGE_NAME_WITH_REGISTRY=ghcr.io/${{ secrets.GH_USERNAME }}/uparzone-v2/prod" >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=ghcr.io/${{ secrets.GH_USERNAME }}/uparzone-v2/prod:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "CAPROVER_GIT_COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PAT_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          cd ./
          docker build -t $FULL_IMAGE_NAME \
                       -t $IMAGE_NAME_WITH_REGISTRY:latest \
                       -f $DOCKERFILE .
          docker push $FULL_IMAGE_NAME
          docker push $IMAGE_NAME_WITH_REGISTRY:latest

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: ${{ secrets.CAPROVER_HOST }}
          app: 'uparzone-v2-prod'
          token: ${{ secrets.CAPROVER_APP_TOKEN }}
          image: ghcr.io/${{ secrets.GH_USERNAME }}/uparzone-v2/prod:${{ github.sha }}

